# Generated by Django 3.1.6 on 2021-02-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_prix'),
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier_item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='panier_item',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.produit'),
        ),
    ]
