# Generated by Django 3.1.6 on 2021-02-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_auto_20210216_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier_item',
            name='prix',
        ),
    ]
