# Generated by Django 3.1.6 on 2021-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menu_categorie'),
        ('paiement', '0003_remove_panier_item_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='menus',
            field=models.ManyToManyField(to='restaurant.Menu'),
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(to='restaurant.Produit'),
        ),
    ]
