# Generated by Django 3.1.6 on 2021-02-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menu_categorie'),
        ('paiement', '0004_auto_20210217_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Panier_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('menus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menu')),
            ],
        ),
        migrations.AlterField(
            model_name='panier',
            name='menus',
            field=models.ManyToManyField(to='paiement.Panier_menu'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(to='paiement.Panier_produit'),
        ),
    ]
