# Generated by Django 3.1.6 on 2021-02-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_auto_20210217_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier_menu',
            old_name='menus',
            new_name='menu',
        ),
    ]
