# Generated by Django 3.1.6 on 2021-02-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0009_commande_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_postale',
            field=models.CharField(default='92170', max_length=32),
        ),
    ]
