# Generated by Django 3.1.6 on 2021-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0010_client_code_postale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_postale',
            field=models.CharField(max_length=32),
        ),
    ]
