# Generated by Django 3.1.6 on 2021-02-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0011_auto_20210218_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paiement.panier'),
        ),
    ]
