# Generated by Django 3.1.6 on 2021-02-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0012_auto_20210218_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='p',
            field=models.TextField(null=True),
        ),
    ]
