# Generated by Django 3.1.6 on 2021-02-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0013_commande_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='p',
        ),
    ]
