# Generated by Django 3.1.6 on 2021-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0014_remove_commande_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_totale',
            field=models.FloatField(default=0.0),
        ),
    ]
