# Generated by Django 3.1.6 on 2021-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0015_commande_prix_totale'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='est_livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='est_vue',
            field=models.BooleanField(default=False),
        ),
    ]
