# Generated by Django 3.1.6 on 2021-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0016_auto_20210219_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='reference',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
