# Generated by Django 3.1.6 on 2021-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='restaurant.Ingredient'),
        ),
    ]
