# Generated by Django 3.1.6 on 2021-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210216_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='restaurant.Ingredient'),
        ),
    ]
