# Generated by Django 3.1.6 on 2021-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210216_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
