# Generated by Django 3.1.6 on 2021-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
