# Generated by Django 3.1.6 on 2021-02-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='libelle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
