# Generated by Django 3.1.6 on 2021-02-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210217_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.categorie'),
        ),
    ]
