# Generated by Django 3.1.6 on 2021-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menu_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, to='restaurant.Categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(blank=True, to='restaurant.Categorie'),
        ),
    ]
